FORMAT: 1A
HOST: http://kilgrave.apiblueprint.org/

# kilgrave

Alters the space-time continuum to allow packages to be delivered instantaneously.

## Changes Collection [/changes]

### Get all changes [POST]

+ Request (application/json)

        
        {
            "site": "2016-08-20T10:45:12",
            "distribution_centre": "2016-01-01T09:00:00",
            "site_route": "2017-03-20T19:15:00
        }

+ Response 200 (application/json)

        [
            {
                "site": "/api/changes/site/2016-08-20T10:45:12",
                "distribution_centre": "/api/changes/site/2016-01-01T09:00:00"
            } 
        ]
        
+ Response 204 (application/json)


## Changes for a specific entity [/changes/{entity}/{timestamp}]

### Get changes (site) [GET]

+ Parameters
    + entity (string) - name of entity
    + timestamp (datetime) - timestamp of latest local change
    
+ Response 200 (application/json)

        [
            {
                "data": [
                    {
                        "id": "9829B906-7CA7-4083-8203-94F34A2366F8",
                        "site_id": 17505,
                        "site_type": 1,
                        "is_repairer": 0,
                        "display_name": "BB2326 Tamworth",
                        "default_locker_type_id": 1,
                        "external_id": "2326",
                        "address1": "Tamworth FC",
                        "address2": "The Lamb Ground, Kettlebrook",
                        "town": "Tamworth",
                        "region": "Staff",
                        "postal_code": "B77 1AA",
                        "site_access_information": "Access code: 7-7-0-6",
                        "last_modified": "2015-06-16 16:22:53.020",
                        "notes": "Installed 13/08/07\nIMPS NOTES\nInformation on map. ",
                        "parent_site_id": null
                    }
                ]
            }
        ]