FORMAT: 1A
HOST: http://kilgrave.apiblueprint.org/v0/

# Kilgrave

This document describes the HTTP API to enable handheld scanner integration with ByBox systems.

Using this site you can:

 * Generate sample code in cURL, Java, JavaScript, Node.js, Perl, Python, PHP, Ruby, GO, C#, Visual Basic, Groovy, Objective C, and Swift.
 * View the structural requirements of requests for various HTTP endpoints.
 * View the structure of expected responses and their associated HTTP status codes.

Find out more about [using this documentation](https://blog.apiary.io/2014/03/21/Re-API-Design-for-Humans).

#Authentication

In this documentation BEARER-TOKEN-FROM-AUTHN-API refers to the token obtained from the the ByBox Authentication API.

# Group Version

## /version

### Version [GET]

Gets the version of the API

+ Response 200 (application/hal+json)

         {
            "majorVersion": 0,
            "minorVersion": 1,
            "patchLevel": 13,
            "buildNumber": 256
         }

# Group Devices

## /device/{deviceId}

Devices represent a physical device that consumes the api. In most cases, this is probably some kind of handheld scanner.

### Create [PUT]

Creates a new device and returns a HAL based representation of urls that must be followed in order to provision this device completely.

+ Parameters
    + deviceId (string) - The unique id of a device, expecting something like an IMEI number

+ Request

    ##### The following defines the body specification for the `PUT` request.
    + `simNumber` (string) -- The `ICCID` number of the sim card in the device
    + `name` (string) -- The `name` of the device
            
    + Body

            {
                "simNumber": "89314404000139171210",
                "name": "My Device"
            }

    + Headers

            Authorization: Bearer BEARER-TOKEN-FROM-AUTHN-API

+ Response 201 (application/hal+json)

         {
            "id": "044524d8-038a-4bc3-ab9c-6531635eef52",
            "deviceId": "990000862471854",
            "simNumber": "89314404000139171210",
            "name": "My Device",
            "status": "Provisioning",
            "_links": {
               "self": {
                  "href": "device/990000862471854",
                  "method": "GET"
               },
               "configure": {
                     "href": "configuration",
                     "method": "GET"
               },
               "sync": {
                     "href": "changes",
                     "method": "POST"
               },
               "complete":{
                     "href": "device/990000862471854/provisioned",
                     "method": "POST"
               }
            }
         }


### By Id [GET]

Gets a device by it's unique id.

+ Parameters
    + deviceId (string) - The uniqe id of a device, expecting something like an IMEI number

+ Request

    + Headers

            Authorization: Bearer BEARER-TOKEN-FROM-AUTHN-API

+ Response 200 (application/hal+json)

         {
           "id": "044524d8-038a-4bc3-ab9c-6531635eef52",
           "deviceId": "990000862471854",
           "simNumber": "89314404000139171210",
           "name": "My Device",
           "status": "InUse",
           "_links":{
             "self":{
                "href": "device/990000862471854",
                "method" : "GET"
             }
           }
         }


## /device/{deviceId}/provisioned

### Provisioned [POST]

Updates the device to mark it as provisioned and finalise the provisioning process.

+ Parameters
    + deviceId (string) - The unique id of the device

+ Request

    + Headers
    
            Authorization: Bearer BEARER-TOKEN-FROM-AUTHN-API

+ Response 200 (text/plain; charset=utf-8)

# Group Configuration

Configuration represents the server held configuration for this system.

## /configuration

### Load [GET]

+ Request

    + Headers

            Authorization: Bearer BEARER-TOKEN-FROM-AUTHN-API

+ Response 200 (application/hal+json)

         {
           "_links":{
             "self":{
                "href": "configuration",
                "method" : "GET"
              }
            }
         }

# Group Events

The events endpoint is responsible for providing a means to allow a client to post events to the server, examples of events might be `ItemDelivered`, `ItemScannedToCage`, etc.

## /events

### Create [POST]

+ Request (application/json)

    + Headers
    
            Authorization: Bearer BEARER-TOKEN-FROM-AUTHN-API

    + Body    

            {
              "events": [
              
              ]
            }

+ Response 201 (text/plain; charset=utf-8)

# Group Changes

The changes endpoint is responsible for providing changed data from the server and for exposing a means to allow a client to figure out what
has changed.

## /changes

Returns a collection of all entity types that have changed on the server.

### Get all [POST]

+ Request (application/hal+json)

    ##### The following defines the body specification for the `POST` request.
    + `includeDeletes` (boolean) -- Should delete based hal links be included in the response
    + `lastModifieds` (object)
        + `site` (timestamp) -- The `lastModified` date of local site data
        + `distributionCentre` (timestamp) -- The `lastModified` date of local distribution centre data
        + `siteRoute` (timestamp) -- The `lastModified` date of local site route data
        + `trunkRoute` (timestamp) -- The `lastModified` date of local trunk route data
        + `trunkRouteLeg` (timestamp) -- The `lastModified` date of local trunk route leg data
        + `trip` (timestamp) -- The `lastModified` date of local trip data
        + `tripItem` (timestamp) -- The `lastModified` date of local trip item data
            
    + Body

            "includeDeletes": false,
            "lastModifieds": {
                "site": "2016-08-20T10:45:12",
                "distributionCentre": "2016-01-01T09:00:00",
                "siteRoute": "2017-03-20T19:15:00
                "trunkRoute": "2016-01-01T09:00:00",
                "trunkRouteLeg": "2016-01-01T09:00:00",
                "trip": "2016-01-01T09:00:00",
                "tripItem": "2016-01-01T09:00:00",
            }

    + Headers

            Authorization: Bearer BEARER-TOKEN-FROM-AUTHN-API

+ Response 200 (application/hal+json)

         {
            "_links": {
               "self": {
                  "href": "changes",
                  "method" : "POST"
               },
               "changes/site": {
                     "href": "changes/site/20160820T104512",
                     "method" : "GET"
               },
               "deletes/site": {
                     "href": "deletes/site/20160820T104512",
                     "method" : "GET"
               },
               "changes/distributionCentre": {
                     "href": "changes/distributionCentre/20160101T090000",
                     "method" : "GET"
               },
               "changes/trunkRoute": {
                     "href": "changes/trunkRoute/20160101T090000",
                     "method" : "GET"
               },
               "changes/trunkRouteLeg": {
                     "href": "changes/trunkRouteLeg/20160101T090000",
                     "method" : "GET"
               }
            }
         }

        
+ Response 204 (text/plain; charset=utf-8)

## /changes/distributionCentre/{timestamp}/{page}

Returns a collection of all distribution centre data changed on the server after a given date.

### Get by timestamp [GET]

+ Parameters
    + timestamp (datetime) - timestamp of latest local change
    + page (int, optional) - the page of data to return
        + Default: `1`

+ Request 

    + Headers

            Authorization: Bearer BEARER-TOKEN-FROM-AUTHN-API

    
+ Response 200 (application/hal+json)

        {
            "totalChanges": 50,
            "_embedded": [
                {
                    "id": "2529B478-7CA7-4092-8203-94F34A2366F8",
                    "identifier": 175,
                    "description": "ByBox UAT Coventry NDC (BBC)",
                    "abbreviation": "BBC",
                    "hub": false,
                    "lastModified": "2015-06-16 16:22:53.020"
                }
            ],
            "_links": {
                "self":{
                   "href": "changes/distributionCentre/20160820T104512/1",
                   "method" : "GET"
                },
                "next":{
                    "href": "changes/distributionCentre/20160820T104512/2",
                    "method" : "GET"
                },
            }
        }
        

## /changes/site/{timestamp}/{page}

Returns a collection of all site data changed on the server after a given date.

### Get by timestamp [GET]

+ Parameters
    + timestamp (datetime) - timestamp of latest local change
    + page (int, optional) - the page of data to return
        + Default: `1`

+ Request 

    + Headers

            Authorization: Bearer BEARER-TOKEN-FROM-AUTHN-API
    
+ Response 200 (application/hal+json)

        {
            "currentPage": 1,
            "totalResults": 9,
            "totalPages": 2,
            "_embedded": [
                {
                    "id": "9829B906-7CA7-4083-8203-94F34A2366F1",
                    "siteId": 1,
                    "siteType": 1,
                    "isRepairer": 0,
                    "displayName": "Site 1",
                    "defaultLockerType": "LockBox",
                    "externalId": "2321",
                    "address1": "Site 1 Address1",
                    "address2": "Site 1 Address2",
                    "town": "Site 1 Town",
                    "region": "Staff",
                    "postalCode": "B77 1AA",
                    "siteAccessInformation": "Access code: XXXX",
                    "lastModified": "2015-06-16 16:22:53.020",
                    "notes": "Installed on XX-XX-XXXX. ",
                    "parentSiteId": null
                },
                {
                    "id": "9829B906-7CA7-4083-8203-94F34A2366F2",
                    "siteId": 2,
                    "siteType": 1,
                    "isRepairer": 0,
                    "displayName": "Site 2",
                    "defaultLockerType": "LockBox",
                    "externalId": "2322",
                    "address1": "Site 2 Address1",
                    "address2": "Site 2 Address2",
                    "town": "Site 2 Town",
                    "region": "Staff",
                    "postalCode": "B77 1AA",
                    "siteAccessInformation": "Access code: XXXX",
                    "lastModified": "2015-06-16 16:22:53.020",
                    "notes": "Installed on XX-XX-XXXX. ",
                    "parentSiteId": null
                },
                {
                    "id": "9829B906-7CA7-4083-8203-94F34A2366F3",
                    "siteId": 3,
                    "siteType": 1,
                    "isRepairer": 0,
                    "displayName": "Site 3",
                    "defaultLockerType": "LockBox",
                    "externalId": "2323",
                    "address1": "Site 3 Address1",
                    "address2": "Site 3 Address2",
                    "town": "Site 3 Town",
                    "region": "Staff",
                    "postalCode": "B77 1AA",
                    "siteAccessInformation": "Access code: XXXX",
                    "lastModified": "2015-06-16 16:22:53.020",
                    "notes": "Installed on XX-XX-XXXX. ",
                    "parentSiteId": null
                },
                {
                    "id": "9829B906-7CA7-4083-8203-94F34A2366F4",
                    "siteId": 4,
                    "siteType": 1,
                    "isRepairer": 0,
                    "displayName": "Site 4",
                    "defaultLockerType": "LockBox",
                    "externalId": "2324",
                    "address1": "Site 4 Address1",
                    "address2": "Site 4 Address2",
                    "town": "Site 4 Town",
                    "region": "Staff",
                    "postalCode": "B77 1AA",
                    "siteAccessInformation": "Access code: XXXX",
                    "lastModified": "2015-06-16 16:22:53.020",
                    "notes": "Installed on XX-XX-XXXX. ",
                    "parentSiteId": null
                },
                {
                    "id": "9829B906-7CA7-4083-8203-94F34A2366F5",
                    "siteId": 5,
                    "siteType": 1,
                    "isRepairer": 0,
                    "displayName": "Site 5",
                    "defaultLockerType": "LockBox",
                    "externalId": "2325",
                    "address1": "Site 5 Address1",
                    "address2": "Site 5 Address2",
                    "town": "Site 5 Town",
                    "region": "Staff",
                    "postalCode": "B77 1AA",
                    "siteAccessInformation": "Access code: XXXX",
                    "lastModified": "2015-06-16 16:22:53.020",
                    "notes": "Installed on XX-XX-XXXX. ",
                    "parentSiteId": null
                }
            ],
            "_links": {
                "self":{
                   "href": "changes/site/20160820T104512/1",
                   "method" : "GET"
                },
                "next":{
                    "href": "changes/site/20160820T104512/2",
                    "method" : "GET"
                },
            }
        }
        

## /changes/site/{timestamp}/2

Returns a collection of all site data changed on the server after a given date.

### Get by timestamp (page 2) [GET]

+ Parameters
    + timestamp (datetime) - timestamp of latest local change
    + page (int, optional) - the page of data to return
        + Default: `1`

+ Request 

    + Headers

            Authorization: Bearer BEARER-TOKEN-FROM-AUTHN-API
    
+ Response 200 (application/hal+json)

        {
            "currentPage": 2,
            "totalResults": 9,
            "totalPages": 2,
            "_embedded": [
                {
                    "id": "9829B906-7CA7-4083-8203-94F34A2366F6",
                    "siteId": 6,
                    "siteType": 1,
                    "isRepairer": 0,
                    "displayName": "Site 6",
                    "defaultLockerType": "LockBox",
                    "externalId": "2326",
                    "address1": "Site 6 Address1",
                    "address2": "Site 6 Address2",
                    "town": "Site 6 Town",
                    "region": "Staff",
                    "postalCode": "B77 1AA",
                    "siteAccessInformation": "Access code: XXXX",
                    "lastModified": "2015-06-16 16:22:53.020",
                    "notes": "Installed on XX-XX-XXXX. ",
                    "parentSiteId": null
                },
                {
                    "id": "9829B906-7CA7-4083-8203-94F34A2366F7",
                    "siteId": 7,
                    "siteType": 1,
                    "isRepairer": 0,
                    "displayName": "Site 7",
                    "defaultLockerType": "LockBox",
                    "externalId": "2327",
                    "address1": "Site 7 Address1",
                    "address2": "Site 7 Address2",
                    "town": "Site 7 Town",
                    "region": "Staff",
                    "postalCode": "B77 1AA",
                    "siteAccessInformation": "Access code: XXXX",
                    "lastModified": "2015-06-16 16:22:53.020",
                    "notes": "Installed on XX-XX-XXXX. ",
                    "parentSiteId": null
                },
                {
                    "id": "9829B906-7CA7-4083-8203-94F34A2366F8",
                    "siteId": 8,
                    "siteType": 1,
                    "isRepairer": 0,
                    "displayName": "Site 8",
                    "defaultLockerType": "LockBox",
                    "externalId": "2328",
                    "address1": "Site 8 Address1",
                    "address2": "Site 8 Address2",
                    "town": "Site 8 Town",
                    "region": "Staff",
                    "postalCode": "B77 1AA",
                    "siteAccessInformation": "Access code: XXXX",
                    "lastModified": "2015-06-16 16:22:53.020",
                    "notes": "Installed on XX-XX-XXXX. ",
                    "parentSiteId": null
                },
                {
                    "id": "9829B906-7CA7-4083-8203-94F34A2366F9",
                    "siteId": 9,
                    "siteType": 1,
                    "isRepairer": 0,
                    "displayName": "Site 9",
                    "defaultLockerType": "LockBox",
                    "externalId": "2329",
                    "address1": "Site 9 Address1",
                    "address2": "Site 9 Address2",
                    "town": "Site 9 Town",
                    "region": "Staff",
                    "postalCode": "B77 1AA",
                    "siteAccessInformation": "Access code: XXXX",
                    "lastModified": "2015-06-16 16:22:53.020",
                    "notes": "Installed on XX-XX-XXXX. ",
                    "parentSiteId": null
                }
            ],
            "_links": {
                "self":{
                   "href": "changes/site/20160820T104512/2",
                   "method" : "GET"
                }
            }
        }
        
## /changes/siteRoute/{timestamp}/{page}

Returns a collection of all site route data changed on the server after a given date.

### Get by timestamp [GET]

+ Parameters
    + timestamp (datetime) - timestamp of latest local change
    + page (int, optional) - the page of data to return
        + Default: `1`

+ Request 

    + Headers

            Authorization: Bearer BEARER-TOKEN-FROM-AUTHN-API

+ Response 200 (application/hal+json)

        {
            "totalChanges": 50,
            "_embedded": [
                {
                    "id": "1427B906-7CA7-4083-8203-94F34A2366F8",
                    "siteId": 17505,
                    "routeCode": "691",
                    "routeType": "Delivery",
                    "abbreviation": "BBC",
                    "description": "BBC-691-D",
                    "lastModified": "2015-06-16 16:22:53.020"
                }
            ],
            "_links": {
                "self":{
                   "href": "changes/siteRoute/20160820T104512/1",
                   "method" : "GET"
                },
                "next":{
                    "href": "changes/siteRoute/20160820T104512/2",
                    "method" : "GET"
                },
            }
        }

## /changes/trunkRoute/{timestamp}/{page}

Returns a collection of all trunk route data changed on the server after a given date.

### Get by timestamp [GET]

+ Parameters
    + timestamp (datetime) - timestamp of latest local change
    + page (int, optional) - the page of data to return
        + Default: `1`

+ Request

    + Headers

            Authorization: Bearer BEARER-TOKEN-FROM-AUTHN-API
    
+ Response 200 (application/hal+json)

        {
            "totalChanges": 50,
            "_embedded": [
                {
                    "id": "9829B906-7CA7-4083-8203-94F34A2366F8",
                    "fromDcIdentifier": 1,
                    "toDcIdentifier": 1,
                    "lastModified": "2017-06-16 16:22:53.020"
                }
            ],
            "_links": {
                "self":{
                   "href": "changes/trunkRoute/20160820T104512/1",
                   "method" : "GET"
                },
                "next":{
                    "href": "changes/trunkRoute/20160820T104512/2",
                    "method" : "GET"
                },
            }
        }

## /changes/trunkRouteLeg/{timestamp}/{page}

Returns a collection of all trunk route leg data changed on the server after a given date.

### Get by timestamp [GET]

+ Parameters
    + timestamp (datetime) - timestamp of latest local change
    + page (int, optional) - the page of data to return
        + Default: `1`

+ Request

    + Headers

            Authorization: Bearer BEARER-TOKEN-FROM-AUTHN-API

    
+ Response 200 (application/hal+json)

        {
            "totalChanges": 50,
            "_embedded": [
                {
                    "id": "9829B906-7CA7-4083-8203-94F34A2366F8",
                    "trunkRouteId": 1,
                    "dcIdentifier": 1,
                    "sequence": 1,
                    "lastModified": "2017-06-16 16:22:53.020"
                }
            ],
            "_links": {
                "self":{
                   "href": "changes/trunkRouteLeg/20160820T104512/1",
                   "method" : "GET"
                },
                "next":{
                    "href": "changes/trunkRouteLeg/20160820T104512/2",
                    "method" : "GET"
                },
            }
        }

## /changes/trip/{timestamp}/{page}

Returns a collection of all trip data changed on the server after a given date.

### Get by timestamp [GET]

+ Parameters
    + timestamp (datetime) - timestamp of latest local change
    + page (int, optional) - the page of data to return
        + Default: `1`

+ Request

    + Headers

            Authorization: Bearer BEARER-TOKEN-FROM-AUTHN-API
    
+ Response 200 (application/hal+json)

        {
            "totalChanges": 50,
            "_embedded": [
                {
                    "id": "0349B236-8CA7-4083-8203-94F34A2366F8",
                    "name": "691-D",
                    "date": "2017-08-16 16:22:53.020",
                    "dc": 195,
                    "status": "Loading",
                    "manifestVersion": 1,
                    "vehicle": "YS06 VDZ",
                    "type": "RoutePlanned",
                    "lastModified": "2017-06-16 16:22:53.020"
                },
                {
                    "id": "0119B236-8CA7-4083-8203-94F34A2366F8",
                    "name": "692-D",
                    "date": "2017-08-16 16:22:53.020",
                    "dc": 195,
                    "status": "Loading",
                    "manifestVersion": 1,
                    "vehicle": "YS06 VDZ",
                    "type": "RoutePlanned",
                    "lastModified": "2017-06-16 16:22:53.020"
                }
            ],
            "_links": {
                "self":{
                   "href": "changes/trip/20160820T104512/1",
                   "method" : "GET"
                },
                "next":{
                    "href": "changes/trip/20160820T104512/2",
                    "method" : "GET"
                },
            }
        }

## /changes/tripitem/{timestamp}/{page}

Returns a collection of all trip item data changed on the server after a given date.

### Get by timestamp [GET]

+ Parameters
    + timestamp (datetime) - timestamp of latest local change
    + page (int, optional) - the page of data to return
        + Default: `1`

+ Request

    + Headers

            Authorization: Bearer BEARER-TOKEN-FROM-AUTHN-API
    
+ Response 200 (application/hal+json)

        {
            "totalChanges": 50,
            "_embedded": [
                {
                    "id": "0449B265-8CA7-4083-8203-94F34A2366F8",
                    "tripId": "0349B236-8CA7-4083-8203-94F34A2366F8",
                    "consignmentCode": "020200230601",
                    "deliverToSiteId": 20495,
                    "status": "DeliveredToLockBox",
                    "deliveryGroup": "203131",
                    "hazardousMaterial": false,
                    "lastModified": "2017-06-16 16:22:53.020"
                },
                {
                    "id": "0549B265-8CA7-4083-8203-94F34A2366F8",
                    "tripId": "0349B236-8CA7-4083-8203-94F34A2366F8",
                    "consignmentCode": "020200230602",
                    "deliverToSiteId": 20495,
                    "status": "DeliveredToLockBox",
                    "deliveryGroup": "203131",
                    "hazardousMaterial": false,
                    "lastModified": "2017-06-16 16:22:53.020"
                }
            ],
            "_links": {
                "self":{
                   "href": "changes/tripitem/20160820T104512/1",
                   "method" : "GET"
                },
                "next":{
                    "href": "ls tochanges/tripitem/20160820T104512/2",
                    "method" : "GET"
                },
            }
        }

# Group Deletes

Returns a collection of all entity types that have been deleted on the server.

## /deletes/site/{timestamp}

Returns a collection of all site data deleted on the server after a given date.

### Get by timestamp [GET]

+ Parameters
    + timestamp (datetime) - timestamp of latest local change

+ Request (application/hal+json)

    + Headers

            Authorization: Bearer BEARER-TOKEN-FROM-AUTHN-API

+ Response 200 (application/hal+json)

         {                                                                                                                                                                                                                                   
           "totalResults": 1,                                                                                                                                                                                                                
           "_embedded": [                                                                                                                                                                                                                    
             "4bc930ea-0d4a-4cd0-b22b-43577baef2f0"                                                                                                                                                                                          
           ],                                                                                                                                                                                                                                
           "_links": {                                                                                                                                                                                                                       
             "self": {                                                                                                                                                                                                                       
               "href": "deletes/site/20170911T105449",                                                                                                                                                                                       
               "method": "GET"                                                                                                                                                                                                               
             }                                                                                                                                                                                                                               
           }                                                                                                                                                                                                                                 
         } 


# Group Data Structures

## Device (object)

+ id: `990000862471854` (string)

    The ID of the device, something like an IMEI number.

+ name: `My Scanner` (string)

    The name of the device.

+ simNumber: `89314404000139171210` (int)

    The ICCID number of the sim card in the device.

+ status: `InUse` (enum[string])
    + Members
        + `Provisioning`
        + `InUse`
        + `SentForRepair`

    The status of the device.

+ lastModified: `2017-06-16 16:22:53.020` (datetime)

    The datetime the site route was last modified.

## Site(object)

+ id: `1427B906-7CA7-5083-8203-94F34A2366F8` (guid)

    The ID of the site.

+ siteId: `17505` (int)

    The ID of the site.

+ siteType: `ExchangeSite` (enum[string])
    + Members
        + `Unknown`
        + `ExchangeSite`
        + `CustomerCollectionSite`
        + `GoldfishRerouteCentre`

    The type of the site.

+ isRepairer: `false` (boolean)

    Is the site a repair site. 

+ displayName: `BB2326 Tamworth` (string)

    The name of the site.

+ defaultLockerType: `LockBox` (enum[string])
    + Members
        + `Unknown`
        + `IBox`
        + `LockBox`
        + `VBox`
        + `HomeDelivery`
        + `CustomerCollection`
        + `VBoxDayDelivery`
        + `PUDO`
        + `RepairAgent`
        + `ThinventoryWarehouse`
        + `NextDayToSite`
        + `InBoot`
        + `ElectronicLockBox`

    The default lock type for the site.

+ externalId: `2326` (string)

    The external identifier for the site.

+ address1: `Tamworth FC` (string)

    The address of the site.

+ address2: `The Lamb Ground, Kettlebrook` (string)

    The address of the site.

+ town: `Tamworth` (string)

    The address of the site.

+ region: `Staff` (string)

    The address of the site.

+ postalCode: `B77 1AA` (string)

    The postal code of the site.

+ siteAccessInformation: `Access code: XYZ` (string)

    The access details for the site.

+ lastModified: `2017-06-16 16:22:53.020` (datetime)

    The datetime the site route was last modified.

+ notes: `Install on date XX-XX-XXXX` (string)

    Any notes related to the site.

+ parentSiteId: `999` (int)

    The ID of the parent site.

## SiteRoute (object)

+ id: `1427B906-7CA7-4083-8203-94F34A2366F8` (guid)

    The ID of the site route.

+ siteId: `17505` (int)

    The ID of the site.

+ routeCode: `691` (string)

    The code associated with the route

+ routeType: `Delivery` (enum[string])
    + Members
        + `Delivery`
        + `Collection`

    The type of the route.

+ abbreviation: `BBC` (string)

    The abbreviation for the route.

+ description: `BBC-691-D` (string)

    The description for the route.

+ lastModified: `2017-06-16 16:22:53.020` (datetime)

    The datetime the site route was last modified.

## Trip (object)

+ id: `1427B906-7CA7-4083-8203-94F34A2366F8` (guid)

    The ID of the trip.

+ name: `691-D` (string)

    The name of the trip.

+ dc: `195` (int)

    The dc handling the trip.

+ status: `Loading` (enum[string])
    + Members
        + `Planning`
        + `AwaitingLoading`
        + `Loading`
        + `AwaitingManifest`
        + `AwaitingDeparture`
        + `InProgress`
        + `Unloading`
        + `AwaitingDebrief`
        + `Debriefing`
        + `Complete`
        + `Closed`
        + `Cancelled`

    The status of the trip.

+ manifestVersion: `1` (int)

    The numerically increasing version of the manifest.

+ vehicle: `BBC-691-D` (string)

    The registration number of the vehicle carrying out the trip. For unplanned trips this won't be present.

+ type: `Loading` (enum[string])
    + Members
        + `Planned`
        + `Unplanned`

    The type of trip.

+ lastModified: `2017-06-16 16:22:53.020` (datetime)

    The datetime the site route was last modified.

## TripItem (object)

+ id: `0449B265-8CA7-4083-8203-94F34A2366F8` (guid)

    The id of the trip item.

+ tripId: `0349B236-8CA7-4083-8203-94F34A2366F8` (guid)

    The id of the trip on which this item is loaded.

+ consignmentCode: `020200230601` (string)

    The consignment code of the item.

+ deliverToSiteId: `20495` (int)

    The id of the site where the item is to be delivered.

+ status: `DeliveredToLockBox` (enum[string])
    + Members
        + `CreatedByDK`
        + `CreatedByDevice`
        + `CollectedFromCustomerSite`
        + `UnloadedFromVehicle`
        + `ReturnCollectedFromLockBox`
        + `StockTakeFromLockBox`
        + `DeliveredToLockBox`
        + `ReturnCollectedFromiBox`
        + `ExpiryCollectedFromiBox`
        + `DeliveredToiBox`
        + `ReturnDeliveredToCustomer`
        + `ExceptionRaisedNonDelivery`
        + `ReturnCollectedFromInBoot`
        + `DeliveredToInBoot`

    The status of the item.

+ deliveryGroup: `20495` (int)

    The delivery group of the item (used to group items delivered to the same physical site but different logical location).

+ hazardousMaterial: `false` (boolean)
    
    Indicates if the item is/contains hazardous material.

+ lastModified: `2017-06-16 16:22:53.020` (datetime)

    The datetime the site route was last modified.
